import { ListView, VerticalBox } from "std-widgets.slint";
import { LineEditBase } from "line-edit.slint";

export struct AppItem {
    app_name: string,
    app_id: string,
    exec: string,
    comment: string,
    icon: image,
}

struct GridConfig {
    enabled: bool,
    col: int,
    row: int,
}

export struct ThemeSlint {
    fullscreen: bool,
    grid_config: GridConfig,
    window-background: color,
    selected-item-background: color,
    selected-text-color: color,
    unselected-text-color: color,
    item-height: length,
    item-spacing: length,
    item-border-radius: length,
    icon-size: length,
    input-font-size: length,
    input-border-width: length,
    text-font-size: length,
    comment-font-size: length,
    font-family: string,
    font-weight: int,
    window-width: length,
    window-height: length,
    window-border-width: length,
    input-height: length,
    animation-time: duration}

export global Palette {
    in property <color> foreground-color;
    in property <color> background-color;
}

export component AppWindow inherits Window {
    in property <ThemeSlint> theme;

    property <length> window_width: theme.window-width;
    property <length> window_height: theme.window-height;
    no-frame: true;
    title: "Cosmic Wanderer";

    in-out property <[AppItem]> appItems;
    in-out property <bool> focused: true;
    in-out property <bool> scopeFocused: true;
    in-out property <int> selected_index: 0;
    in-out property <string> text_input;
    callback focus_changed(bool);
    callback text_entered(string);
    callback item_clicked(int);

    public function focusText() {
        input.focus();
    }
    public function focusMain() {
        focus_handler.focus();
    }
    public function readFocus() -> bool {
        root.focused = TextInputInterface.text-input-focused;
        root.focus_changed(root.focused);
        return root.focused;
    }
    public function select_item(index: int) {
        root.selected_index = index;
    }
    public function set_scroll(scroll_y: length) {
        list.viewport_y = scroll_y;
    }

    if !root.theme.grid_config.enabled: Rectangle {
        border-width: root.theme.window-border-width;
        clip: false;
        background: root.theme.window-background;
        border-color: root.theme.selected-item-background;
        border-radius: root.theme.item-border-radius;
        height: root.theme.window-height - root.theme.input-height;
        width: root.theme.window-width * 0.96;
        y: root.theme.input-height;
        x: root.theme.window-width * 0.02;
    }

    Rectangle {
        border-width: root.theme.input-border-width;
        clip: false;
        background: root.theme.window-background;
        border-color: root.theme.selected-item-background;
        border-radius: root.theme.item-border-radius;
        width: root.theme.window-width * 0.96;
        x: root.theme.window-width * 0.02;
        y: root.theme.window-width * 0.02;
        height: root.theme.input-height * 0.80;
    }

    forward-focus: focus_handler;
    focus_handler := FocusScope {
        focus-changed-event() => {
            root.scopeFocused = self.has-focus;
            root.focus_changed(root.focused);
        }

        key-pressed(event) => {
            if (event.text == Key.Escape) {
                root.scopeFocused = false;
                root.focus_changed(root.focused);
            }
            accept
        }

        input := LineEditBase {
            text <=> root.text_input;
            font: root.theme.font-family;
            text-color: root.theme.unselected-text-color;
            margin: 10px;
            horizontal-alignment: left;
            width: parent.width * 0.96 - 16px;
            x: window-width * 0.02 + 16px;
            y: window-width * 0.02;
            height: root.theme.input-height * 0.80;

            font-size: root.theme.input-font-size;

            key-pressed(event) => {
                if (event.text == Key.Escape) {
                    root.scopeFocused = false;
                    root.focus_changed(root.scopeFocused);
                    accept
                }
                if (event.text == Key.UpArrow) {
                    if (root.selected_index * root.theme.item-height < -list.viewport_y) {
                        root.selected_index = Math.floor((-list.viewport_y + window-height - root.theme.item-height * 2) / root.theme.item-height);
                        if (root.selected_index < 0) {
                            root.selected_index = 0;
                        }
                    } else if (root.selected_index > 0) {
                        root.selected_index -= 1;
                        if (root.selected_index * root.theme.item-height < -list.viewport_y + root.theme.item-height) {
                            list.viewport_y = -root.selected_index * root.theme.item-height + root.theme.item-height;
                        }
                    }
                    accept
                }
                if (event.text == Key.DownArrow) {
                    if (root.selected_index * root.theme.item-height < -list.viewport_y) {
                        root.selected_index = (((-list.viewport_y) / root.theme.item_height).floor()) + 1;
                        if (root.selected_index < 0) {
                            root.selected_index = 0;
                        }
                    } else if (root.selected_index < root.appItems.length - 1) {
                        root.selected_index += 1;
                        if ((root.selected_index + 1) * root.theme.item-height > (-list.viewport_y + window-height - root.theme.item-height * 2)) {
                            list.viewport_y = -(root.selected_index * root.theme.item-height - (window-height - 150px) + root.theme.item-height);
                        }
                    }
                    accept
                }
                if (event.text == Key.PageDown) {
                    root.selected_index = Math.min(
        root.selected_index + Math.max(1, Math.floor(window_height / root.theme.item_height) - 2),
        root.appItems.length - 1);
                    list.viewport_y = -root.selected_index * root.theme.item_height + root.theme.item_height;
                    accept
                }
                if (event.text == Key.PageUp) {
                    root.selected_index = Math.max(
        root.selected_index - Math.max(1, Math.floor(window_height / root.theme.item_height) - 2),
        0);
                    list.viewport_y = -root.selected_index * root.theme.item_height + root.theme.item_height;
                    accept
                }
                reject
            }

            accepted => {
                root.item_clicked(selected_index);
            }

            edited => {
                root.text_entered(self.text);
            }
        }

        VerticalLayout {
            x: 0;
            width: window_width;
            Rectangle {
                height: root.theme.input-height * 1.09;
            }

            list := ListView {
                enabled: !root.theme.grid_config.enabled;
                visible: !root.theme.grid_config.enabled;
                width: parent.width * 0.92;
                height: window-height - root.theme.input-height * 1.18;
                x: ((parent.width - self.width) / 2);
                for data[idx] in root.appItems: VerticalLayout {
                    height: root.theme.item-height;
                    width: parent.width;
                    spacing: root.theme.item-spacing;
                    padding-top: 0px;
                    touch_list := TouchArea {

                        Rectangle {
                            clip: false;
                            height: root.theme.item-height - 4px;
                            border-radius: root.theme.item-border-radius;
                            background: touch_list.has-hover || idx == selected_index ? root.theme.selected-item-background : rgb(0,0,0,0);
                            animate background { duration: root.theme.animation-time; }
                            x: 0px;
                            width: parent.width;
                        }

                        Text {
                            font-weight: root.theme.font-weight;
                            overflow: elide;
                            font-family: root.theme.font-family;
                            font-size: root.theme.text-font-size;
                            x: window-width * 0.1825;
                            y: data.comment == "" ? root.theme.item-height * 0.3 : root.theme.item-height * 0.12;
                            height: root.theme.text-font-size + 5px;
                            width: window-width - (root.theme.icon-size + 25px) - 40px;
                            vertical-alignment: top;
                            text: data.app_name;
                            color: touch_list.has-hover || idx == selected_index ? root.theme.selected-text-color : root.theme.unselected-text-color;
                            animate color { duration: root.theme.animation-time; }
                        }

                        Text {
                            font-weight: root.theme.font-weight;
                            font-family: root.theme.font-family;
                            font-size: root.theme.comment-font-size;
                            x: window-width * 0.1825;
                            y: root.theme.item-height * 0.40;
                            height: root.theme.item-height * 0.55;
                            width: window-width - (root.theme.icon-size + 25px) - 40px;
                            wrap: word-wrap;
                            text: data.comment;
                            overflow: elide;
                            color: touch_list.has-hover || idx == selected_index ? root.theme.selected-text-color : root.theme.unselected-text-color;
                            animate color { duration: root.theme.animation-time; }
                        }

                        Image {
                            source: data.icon;
                            width: root.theme.icon-size;
                            height: root.theme.icon-size;
                            x: window-width * 0.0375;
                        }

                        clicked => {
                            selected_index = idx;
                            root.item_clicked(idx);
                        }
                    }
                }
            }
        }

        in-out property <int> current_page: 0;
        property <int> columns: root.theme.grid_config.col;
        property <int> rows: root.theme.grid_config.row;
        VerticalLayout {
            visible: root.theme.grid_config.enabled;

            y: root.theme.input-height * 1.5;

            GridLayout {
                spacing: root.theme.item-spacing;
                height: parent.height * 0.8;

                for data[idx] in root.appItems: touch_grid := TouchArea {
                    private property <int> local_index: idx - current_page * (columns * rows);
                    private property <int> grid_index: local_index < 0 ? 0 : local_index;

                    visible: local_index >= 0 && local_index < (columns * rows);
                    row: grid_index / columns;
                    col: Math.mod(grid_index, columns);
                    min-width: (root.theme.window-width * 0.96) / columns;
                    min-height: ((root.theme.window-height * 0.80) - (root.theme.input-height * 1.09)) / rows;

                    VerticalLayout {
                        Rectangle {
                            border-radius: root.theme.item-border-radius;
                            background: touch_grid.has-hover ? root.theme.selected-item-background : rgb(0,0,0,0);
                        }

                        spacing: 6px;
                        padding: 8px;

                        Image {
                            source: data.icon;
                        }

                        Text {
                            text: data.app_name;
                            overflow: elide;
                        }
                    }

                    clicked => root.item_clicked(idx);
                }
            }

            HorizontalLayout {
                spacing: 20px;
                height: window_height * 0.2;
                alignment: center;

                Rectangle {
                    background: #007acc;
                    Text {
                        text: "Button 1";
                        color: white;
                        horizontal_alignment: center;
                        vertical_alignment: center;
                    }

                    TouchArea {
                        clicked => {
                            current_page = current_page - 1;
                        }
                    }
                }

                Rectangle {
                    width: 100px;
                    height: 40px;
                    background: #007acc;
                    Text {
                        text: "Button 2";
                        color: white;
                        horizontal_alignment: center;
                        vertical_alignment: center;
                    }

                    TouchArea {
                        clicked => {
                            current_page = current_page + 1;
                        }
                    }
                }
            }
        }
    }

    background: rgb(0, 0, 0, 0);
}
